title: Detecting MHW in the LENS2 simulations
author: Kenzie Klisz and Gustavo Marques
logo: images/ncar_logo.png

execute:
  execute_notebooks: 'off'

# Information about where the book exists on the web
repository:
  url: https://github.com/NCAR/MHW_LENS2  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_edit_page_button : true
  use_issues_button    : true
  home_page_in_navbar  : false

