name: analysis
channels:
    - conda-forge
    - nodefaults
dependencies:
    - numpy
    - xarray
    - matplotlib
    - cartopy
    - dask
    - jupyter
    - jupyterlab
    - netCDF4
    - distributed
    - ncar_jobqueue
    - intake
    - holoviews
    - dask
    - scipy
    - intake-esm
    - nc.time.axis
    - distributed
    - pop-tools
    - xesmf 
